version: "3"
services:
  tapiriik:
    build: .
    volumes:
      - ./:/app:rw
      - tapiriik_data:/wamp/www/tapiriik/tapiriik/static:rw
      # - ./tapiriik/local_settings.py:/app/local_settings.py:rw
    environment:
      - RABBITMQ_BROKER_URL=amqp://guest@tapiriik_rabbitmq//
      - MONGO_HOST=mongodb://root:example@tapiriik_mongo:27017/admin
      - REDIS_HOST=tapiriik_redis
    ports:
      - "8087:8000"
    links:
      - tapiriik_redis
      - tapiriik_mongo
      - tapiriik_rabbitmq
  tapiriik_redis:
    image: redis
  tapiriik_mongo:
    image: mongo:5.0.25-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db:rw
  tapiriik_rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
volumes:
  rabbitmq_data:
  mongo_data:
  tapiriik_data:
